### ISSUE TITLE
As a tester, I want there to be methods that return DTOs of the correct type depending on the arguments entered so that I can create DTOs from field names

### ISSUE THREAD

**Issue by trickaby** [trickaby/OpenWeatherFramework#20]
DOD:
Methods in WeatherAPI exist that return DTOs of correct type based on URL
At minimum, by City name, City ID

Testing:
Based on field entered, correct DTO is created

**Comment by samurahh** [comment]
Methods implemented for each query possible. (e.g. by City Name, by City ID, by ZIP code, cities in circle, cities in  rectangle, cities by ids). 
It is infeasible to create a unique method that will return objects of different classes (WeatherListDTO depends on WeatherDTO)
